### ISSUE TITLE
How to match field policy_name in the scan result in routes section

### ISSUE THREAD

**Issue by Git-Kyro** [aquasecurity/postee#184]
I have question about cfg.yaml，
how to match policy_name as a condition, i tried contains(input.image_assurance_results.policy_failures.policy_name, "test") or regex.match("test", input.image_assurance_results), but not successful match,  please let me know how to do that, thanks.

cfg.yaml
```
   routes: 
    - name: test
      input: |
       contains(input.image_assurance_results.policy_failures.policy_name, "test")   or  regex.match("test", input.image_assurance_results)
```

scan result:
```
{
    "image": "192.168.1.74:8081/test/gateway:6.0.21164",
    "registry": "Ad Hoc Scans",
    "image_assurance_results":   
    {
        "policy_failures":
        [
            {
                "policy_id": 6,
                "policy_name": "test",
            }
        ],
    }
}
```
