### ISSUE TITLE
Postee UI does not save some preferences on disk.

### ISSUE THREAD

**Issue by simar7** [aquasecurity/postee#410]
## Description

Postee UI does not save preferences on disk.

## What did you expect to happen?

Upon modifying the Postee config through the UI the changes should be saved on disk.

## What happened instead?

Postee config does not get updated.

## Additional details (environment setup, networking info...):

This is due to actions (previously named as outputs) getting marshalled incorrectly. The actions need to be saved with the key of `actions` but today they are saved with the key of `outputs`.

When Postee backend tries to use them, it doesn't see the key of `actions` within each route.

Incorrect config saved by Postee UI:
```
routes:
  - output: []
    name: send a message when TRC-11 happens
    input-files:
      - ''
    outputs:
      - my-teams
    template: raw-json
    input: contains(input.SigMetadata.ID, "TRC-11")
```

Correct config that should be saved by Postee UI:
```
routes:
  - output: []
    name: send a message when TRC-11 happens
    input-files:
      - ''
    actions:
      - my-teams
    template: raw-json
    input: contains(input.SigMetadata.ID, "TRC-11")
```
