### ISSUE TITLE
Permission issues on EKS

### ISSUE THREAD

**Issue by simar7** [aquasecurity/postee#464]
## Description

A user reported permission issues when running on EKS. See screenshot below for details.

## What did you expect to happen?

No permission issues

## What happened instead?

![image](https://user-images.githubusercontent.com/1254783/190697864-06e12a3c-1a30-4baa-a913-c385e258dd34.png)

## Output of run with `POSTEE_DEBUG=true`:

`No response`

## Additional details (environment setup, networking info...):
EKS cluster 1.20 version

**Comment by grglzrv** [comment]
Fixed by adding podSecurityContext: fsGroup: 1099 It should be activated by default
https://github.com/aquasecurity/postee/blob/main/deploy/helm/postee/values.yaml#L37-L46
```
    podSecurityContext:
      fsGroup: 1099
    securityContext:
      runAsUser: 1099
      runAsGroup: 1099
  ```
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/19932357/191956293-db288912-5d68-4969-a333-9145a3d69965.png">

**Comment by simar7** [comment]
> Fixed by adding podSecurityContext: fsGroup: 1099 It should be activated by default https://github.com/aquasecurity/postee/blob/main/deploy/helm/postee/values.yaml#L37-L46
> 
> ```
>     podSecurityContext:
>       fsGroup: 1099
>     securityContext:
>       runAsUser: 1099
>       runAsGroup: 1099
> ```
> 
> <img alt="image" width="1510" src="https://user-images.githubusercontent.com/19932357/191956293-db288912-5d68-4969-a333-9145a3d69965.png">

thanks for looking into this @grglzrv - are you suggesting the values should be set to default as the following?
```
    podSecurityContext:
      fsGroup: 1099
    securityContext:
      runAsUser: 1099
      runAsGroup: 1099
```
