### ISSUE TITLE
EKS error can't get Postee and PosteeUI running at the same time because of the volumes

### ISSUE THREAD

**Issue by ichasco-heytrade** [aquasecurity/postee#499]
## Description

I am getting errors because 2 services are deployed using the same volume and in EKS, the EBS volumes doesn't support `ReadWriteMany`

```
11m         Warning   FailedAttachVolume             pod/posteeui-55b747754c-wdsr6                         Multi-Attach error for volume "pvc-db7fb209-8020-42a6-995b-c9fa99242c43" Volume is already used by pod(s) postee-0, posteeui-67f5d465fc-bhklv
11m         Warning   FailedAttachVolume             pod/posteeui-55b747754c-wdsr6                         Multi-Attach error for volume "pvc-3e7f965a-dfb3-4121-82f1-0df05e30d046" Volume is already used by pod(s) postee-0, posteeui-67f5d465fc-bhklv
9m53s       Warning   FailedMount                    pod/posteeui-55b747754c-wdsr6                         Unable to attach or mount volumes: unmounted volumes=[postee-config postee-db], unattached volumes=[postee-config kube-api-access-mj9r9 aws-iam-token postee-db]: timed out waiting for the condition
```

Should the UI communicate to postee through an API? or use a DB?

## What did you expect to happen?

Have 2 services running

## What happened instead?

I can only have 1 service running

Postee Chart Version: `v2.9.0`

**Comment by krol3** [comment]
Hi @ichasco-heytrade  I will take a look! Thank you

**Comment by fbuchmeier-abi** [comment]
Hi,

I've also encountered this error and worked around it by using the following podAffinity setting in the Helm Chart:

```
# BUG: postee-0 und posteeui both need access to the same PVC (database) so we need to ensure both run on the same node
affinity:
  podAffinity: 
    requiredDuringSchedulingIgnoredDuringExecution: 
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/instance
          operator: In 
          values:
          - postee
      topologyKey: kubernetes.io/hostname
```

This way both the postee-ui and the postee service run on the same node and volume sharing works. This is not always possible, so either using a RWX volume or a dedicated database would be a better option.

Best regards,
Florian.
