### ISSUE TITLE
How to mount rego templates?

### ISSUE THREAD

**Issue by HW-Jeremy** [aquasecurity/postee#532]
Hi, 

We installed postee with the supplied Helm chart, however it doesn't seem to support volume mounting anywhere other than on the host. Is it possible to modify the chart to support the existing volume mount?

Regards

**Comment by HW-Jeremy** [comment]
UP :)

**Comment by weibo-zhao** [comment]
I have the same issue, later I use the URL to solve the problem.

**Comment by HW-Jeremy** [comment]
@weibo-zhao when you say you use the URL, it's postee-ui?

**Comment by martijnvdp** [comment]
i have postee also deployed with the helm chart and you can make use of the extra mount vars in the chart to mount a template from a configmap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: postee-templates
data:
  trivy-operator-jira.rego: |
    package postee.trivyoperator.jira

    with_default(obj, prop, default_value) = default_value{
    not obj[prop]
    
    etc...
```

values:
```
  # Extra Volumes to add to the postee Statefulset
  extraVolumes:
  - name: jira-template
    configMap:
      name: postee-templates 
      items:
        - key: trivy-operator-jira.rego
          path: trivy-operator-jira.rego
  # Extra Volumes Mounts to add to the postee Statefulset
  extraVolumeMounts: 
    - name: jira-template
      mountPath: /server/rego-templates/trivy-operator-jira.rego
      subPath: trivy-operator-jira.rego
    ```
