### ISSUE TITLE
How to use email action?

### ISSUE THREAD

**Issue by jeff1985** [aquasecurity/postee#622]
Hi I'm trying to configure postee to send report emails:

```
routes:
  - name: email
    actions: [ my-email ]
    template: vuls-html

actions:
 - name: my-email
    type: email
    enable: true
    user:   xxx
    password: xxx
    host: xxx
    port:      587
    sender: xxx
    recipients: xxx
```

I see events are coming in, like:
{"kind":"ExposedSecretReport","apiVersion":"aquasecurity.github.io/v1alpha1" ....

but in the log there is an error:
`2023/10/11 14:57:10 route "email" is associated with template "vuls-html"
2023/10/11 14:57:10 Error while evaluating input: property title is not found`

What does that mean and how can I fix it.

**Comment by afdesk** [comment]
It seems the part of config file is missing with ` template: vuls-html`.
```yaml
templates:
- name: vuls-html                       #  Out of the box HTML template
  rego-package:  postee.vuls.html       #  HTML template REGO package (available out of the box)
```
